# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.35.244.69:5000/krithiva/nodejs-bdd-testing
  tag: 0.0.25
  pullPolicy: IfNotPresent
service:
  name: nodejs-bdd-testing
  type: ClusterIP
  externalPort: 80
  internalPort: 8081
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

podAnnotations:
  jenkins-x.io/cve-image-id: 2a5cc3070e53ed958fcdc8f84aa0c8b6f806ab87147d2b6b042e7adb585e7090
